### ISSUE TITLE
Requirements for setup

### ISSUE THREAD

**Issue by babdulhakim2** [Olamyy/pypayant#6]
The package relies on Python requests. Can you add a requirements section. 'Pip install requests' first before installing pypayant

**Comment by Olamyy** [comment]
The _requests_ package has already been added to the _setup.py_ file. So, when you run _pip install pypayant_ it should automatically install requests for you. 
You can check the _setup.py_ file for more information.

If that doesn't take care of your issue, please, feel free to reopen the issue.
